# .gitlab-ci.yml
image: docker:24.0.5

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t weathermap .

deploy:
  stage: deploy
  script:
    - docker rm -f weathermap || true
    - docker run -d --name weathermap -p 80:3000 weathermap
