image: node:20-alpine

stages:
  - build
  - deploy

# Build Front
build_front:
  stage: build
  script:
    - cd front
    - npm install
    - npm run build
  tags:
    - weather-ci
  artifacts:
    paths:
      - front/build/
    expire_in: 10 minutes

# Build Back
build_back:
  stage: build
  script:
    - cd back
    - npm install
    - npm run build
  tags:
    - weather-ci
  artifacts:
    paths:
      - back/dist/
    expire_in: 10 minutes

# Deploy (les deux)
deploy:
  stage: deploy
  image: docker:24.0.5
  script:
    # FRONT
    - cd front
    - docker build -t weathermap-front .
    - docker stop weathermap-front || true
    - docker rm weathermap-front || true
    - docker run -d --name weathermap-front -p 3000:3000 --restart unless-stopped weathermap-front

    # BACK
    - cd ../back
    - docker build -t weathermap-back .
    - docker stop weathermap-back || true
    - docker rm weathermap-back || true
    - docker run -d --name weathermap-back -p 8080:8080 --restart unless-stopped weathermap-back
  tags:
    - weather-ci
  needs:
    - build_front
    - build_back
