#Définition de l'image
image: node:20-alpine

stages : 
  - build
  - deploy


build : 
  stage : build
  script :
    - npm install
    - npm run build
  tags : 
    - weather-ci

deploy:
  stage: deploy
  image: docker:24.0.5
  script:
    - docker info
    - docker build -t weathermap .
    - docker run -d -p 3000:3000 weathermap
