

stages:
  - build
  - deploy

# Build Front
build_front:
  image: node:20-alpine
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  tags:
    - weather-ci

# Build Back
build_back:
  image: maven:3.9.9-amazoncorretto-17-alpine
  stage: build
  script:
    - cd backend
    - mvn package
  tags:
    - weather-ci

# Deploy (les deux)
deploy:
  stage: deploy
  image: docker:24.0.5
  script:
    # FRONT
    - cd frontend
    - docker build -t weathermap-frontend .
    - docker stop weathermap-frontend || true
    - docker rm weathermap-frontend || true
    - docker run -d --name weathermap-frontend -p 3000:3000 --restart unless-stopped weathermap-frontend

    # BACK
    - cd ../backend
    - docker build -t weathermap-backend .
    - docker stop weathermap-backend || true
    - docker rm weathermap-backend || true
    - docker run -d --name weathermap-backend -p 8080:8080 --restart unless-stopped weathermap-backend
  tags:
    - weather-ci
  needs:
    - build_front
    - build_back
