stages:
  - build
  - deploy

variables:
  DEPLOY_USER: "ubuntu"
  DEPLOY_HOST: "37.187.49.205"
  DEPLOY_PATH: "/home/ubuntu/weathermap"

# Build Frontend
build_front:
  image: node:20-alpine
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
  tags:
    - weather-ci

  

# Build Backend
build_back:
  image: maven:3.9.9-amazoncorretto-17-alpine
  stage: build
  script:
    - cd backend    
    - mvn package
  artifacts:
    paths:
      - backend/target/app.jar
  tags:
    - weather-ci

# Deploy Docker containers
deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_PATH"
    - scp frontend/build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/frontend/
    - scp backend/target/app.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/backend/app.jar
    - scp nginx/conf.d/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/nginx/conf.d/
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker stop weathermap-nginx || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker rm weathermap-nginx || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker stop weathermap-frontend || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker rm weathermap-frontend || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker stop weathermap-backend || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker rm weathermap-backend || true"
    # Backend
    - ssh $DEPLOY_USER@$DEPLOY_HOST " docker run -d --name weathermap-backend-prod -p 8080:8080 -v $DEPLOY_PATH/backend/app.jar:/app/app.jar openjdk:20 java -jar /app/app.jar"

    # Frontend and Nginx
    - ssh $DEPLOY_USER@$DEPLOY_HOST " docker run -d --name weathermap-frontend-prod -p 3000:80 -v $DEPLOY_PATH/frontend:/usr/share/nginx/html nginx:alpine"
    - ssh $DEPLOY_USER@$DEPLOY_HOST " docker run -d --name weathermap-nginx -p 80:80 -v $DEPLOY_PATH/nginx/conf.d:/etc/nginx/conf.d:ro nginx:alpine"
       
  only:
    - deploy/setup-deploy