services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: weathermap-react-vite
    image: weathermap-react-vite
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    
  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: weathermap-springboot
    image: weathermap-springboot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - ./backend/target:/app/target